# General settings
title: Siddhant Garg
title_html: "Siddhant Garg"
description:
  en: Hi! I am a graduate student at the University of Wisconsin-Madison
baseurl: ""
url: "https://sid7954.github.io"

langs: ["en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"

# Author
author: Siddhant Garg

email: sid7954@gmail.com
twitter_username: sid7954
github_username: sid7954
linkedin_username: siddhant-garg
curriculum:
  url: assets/cv_gaalcaras.pdf

# Nav menu
nav_ext_links:
  - name: Blog
    url:
      en: https://sociologs.com/en/

# Piwik
piwik:
  url: batcloud.me/piwik
  site_id: 2

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
remote_theme: sid7954/academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
