# General settings
title: Siddhant Garg
title_html: "<b>ga</b>briel<b><span class=\"invisible\"> </span>alcaras</b>"
description:
  fr: Gabriel Alcaras est doctorant en sociologie, spécialiste des questions numériques et des méthodes quantitatives.
  en: Gabriel Alcaras is a PhD student in sociology, mostly working on digital issues and quantitative methods.
baseurl: ""
url: "https://sid7954.github.io"

langs: ["fr", "en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "fr"

# Author
author: Siddhant Garg

email: sid7954@gmail.com
twitter_username: sid7954
github_username: sid7954
keybase_username: gaalcaras
linkedin_username: gaalcaras
curriculum:
  url: assets/cv_gaalcaras.pdf

# Nav menu
nav_ext_links:
  - name: Blog
    url:
      fr: https://sociologs.com/fr/
      en: https://sociologs.com/en/

# Piwik
piwik:
  url: batcloud.me/piwik
  site_id: 2

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
remote_theme: sid7954/academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
