# General settings
title: Siddhant Garg
title_html: "Siddhant Garg"
url: "https://sid7954.github.io"
description: "Email: sgarg33@wisc.edu"
# Author
author: Siddhant Garg

twitter_username: sid7954
github_username: sid7954
linkedin_username: siddhant-garg
googlescholar : "https://scholar.google.com/citations?user=V02t618AAAAJ&hl=en&oi=ao"
dblp : "https://dblp.org/pers/hd/g/Garg:Siddhant"

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
remote_theme: sid7954/academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
